# Generated by Django 5.2.1 on 2025-06-02 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_type', models.CharField(choices=[('salmon', 'Salmon'), ('tuna', 'Tuna'), ('mackerel', 'Mackerel'), ('prawns', 'Prawns'), ('other', 'Other')], max_length=50)),
                ('quantity_kg', models.FloatField()),
                ('quality_grade', models.CharField(max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('storage_location', models.CharField(max_length=100)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
